### ISSUE TITLE
balance, word and effect suggestions

### ISSUE THREAD

**Issue by pizzalord22** [ketan-ryan/MCRecog#1]
# balance
 1. make up always teleport above ground and not water (harder to abuse) 
 2. rotate the words the cause effects

# word ideas
 1. yikes
 2. buddy

# effect ideas
1. refill 1 hearth
2. spawn a lava source block
3. give 1 iron nugget
4. strength potion effect
5. no effects for x time

**Comment by ketan-ryan** [comment]
1. I made 'up' not work if you're in water, I think there's a good enough chance of him not always being close enough to water to survive anyways
2. I like all the other suggestions

**Comment by pizzalord22** [comment]
maybe also have a check if up does not place you above the world ceiling so that you don't lose items on top of the nether ceiling

**Comment by ketan-ryan** [comment]
Yep good idea

**Comment by ketan-ryan** [comment]
Implemented
